-- ############################################################################
-- BLOCO 6 — NAO TEM SQL PARA COLAR
-- ----------------------------------------------------------------------------
-- A leitura do texto do delegado pela IA usa o que ja existe no banco:
--
--   * `qa_processo_manifestacoes_pf.analise_ia_json` e `.exigencias_json`
--     nasceram na migration 20260816220000, ja aplicada.
--   * As exigencias novas entram em `qa_processo_documentos`, que nao tem
--     CHECK de tipo — o vocabulario fechado esta em `qa_documentos_cliente`,
--     e todos os tipos do cardapio da IA ja passaram a fazer parte dele em
--     20260816250000.
--
-- Ou seja: o ultimo SQL a colar continua sendo o do Bloco 5
-- (20260816260000 — notificado e recurso_administrativo no CHECK de status),
-- que voce ja aplicou e conferiu.
--
-- O teste `exigenciasPFTipos.test.ts` compara o cardapio da IA com o CHECK do
-- banco a cada rodada e falha se os dois divergirem — e o que impede a IA de
-- pedir um documento cujo upload o banco recusaria.
-- ############################################################################
