project_id = "itwsjxijqjximspqtvqk"

[functions.admin-data]
verify_jwt = false

[functions.create-asaas-payment]
verify_jwt = false

[functions.create-asaas-subscription]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.brasil-api-lookup]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.notify-lead]
verify_jwt = false

[functions.send-purchase-confirmation]
verify_jwt = false

[functions.submit-lead]
verify_jwt = false

[functions.admin-auth]
verify_jwt = false

[functions.register-log]
verify_jwt = false

[functions.certificate-manager]
verify_jwt = false

[functions.sign-contract-pdf]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = false

[functions.invoice-reconcile]
verify_jwt = false
