// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-knowledge-base.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var SUPABASE_URL = "https://ogkltfqvzweeqkfmrzts.supabase.co";
var ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9na2x0ZnF2endlZXFrZm1yenRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY4ODc4OTIsImV4cCI6MjA5MjQ2Mzg5Mn0.Bqn76pQvh5f0lfDoucMB8BAo9y3Fs4vnVslbwGg73-g";
var search_knowledge_base_default = defineTool({
  name: "search_knowledge_base",
  title: "Search public knowledge base",
  description: "Search the public Quero Armas legal knowledge base (laws, norms, help articles) and return a synthesized answer with citations. Use for questions about CAC, posse, porte, Ex\xE9rcito, Pol\xEDcia Federal norms.",
  inputSchema: {
    query: z.string().min(3).max(500).describe("Natural language question in Portuguese about Brazilian firearm regulations.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ query }) => {
    try {
      const r = await fetch(`${SUPABASE_URL}/functions/v1/qa-kb-search-cliente`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          apikey: ANON_KEY,
          Authorization: `Bearer ${ANON_KEY}`
        },
        body: JSON.stringify({ query })
      });
      const text = await r.text();
      if (!r.ok) {
        return {
          content: [{ type: "text", text: `Erro na busca (${r.status}): ${text.slice(0, 500)}` }],
          isError: true
        };
      }
      let parsed;
      try {
        parsed = JSON.parse(text);
      } catch {
        return { content: [{ type: "text", text }] };
      }
      const answer = parsed?.answer ?? "Sem resposta.";
      const artigos = Array.isArray(parsed?.articles) ? parsed.articles : [];
      const cites = artigos.slice(0, 5).map((a, i) => `${i + 1}. ${a.title ?? a.titulo ?? "artigo"}`).join("\n");
      const out = cites ? `${answer}

Fontes:
${cites}` : answer;
      return {
        content: [{ type: "text", text: out }],
        structuredContent: { answer, articles: artigos }
      };
    } catch (e) {
      return {
        content: [{ type: "text", text: `Falha ao chamar a base: ${e?.message ?? String(e)}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "quero-armas-mcp",
  title: "Quero Armas MCP",
  version: "0.1.0",
  instructions: "Ferramentas p\xFAblicas do Quero Armas. Use `search_knowledge_base` para consultar a base p\xFAblica de legisla\xE7\xE3o e artigos sobre CAC, posse, porte e normas do Ex\xE9rcito e Pol\xEDcia Federal brasileira.",
  tools: [search_knowledge_base_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
