ALTER TABLE public.qa_itens_venda DROP CONSTRAINT IF EXISTS chk_qa_itens_venda_status;

ALTER TABLE public.qa_itens_venda ADD CONSTRAINT chk_qa_itens_venda_status
CHECK (upper(btrim(status)) = ANY (ARRAY[
  'PAGO','NÃO PAGOU','NAO PAGOU','FALT. PARTE PAG.','DESISTIU','INDEFERIDO','DEFERIDO',
  'MONTANDO PASTA','AGUARDANDO DOCUMENTOS DO CLIENTE','EM ANÁLISE','EM ANALISE',
  'PRONTO PARA ANÁLISE','PRONTO PARA ANALISE','CANCELADO','RESTITUÍDO','RESTITUIDO',
  'CONCLUÍDO','CONCLUIDO','À INICIAR','A INICIAR','À FAZER','A FAZER',
  'AGUARD. ETAPA ANTERIOR','RECURSO ADMINISTRATIVO','AGUARDANDO DOCUMENTAÇÃO',
  'AGUARDANDO DOCUMENTACAO','NOTIFICADO','PASTA FÍSICA - AGUARDANDO LIBERAÇÃO',
  'PASTA FISICA - AGUARDANDO LIBERACAO'
]));